config/routes.rb
AjoContact::Engine.routes.draw do
  root :to => 'contact#index'
  resources :messages, :contact
  match 'thank_you' => 'contact#thank_you', :as => 'contact_thank_you'
end

app/models/ajo_contact/message.rb
module AjoContact
  class Message < ActiveRecord::Base
    attr_accessible :first_name, :last_name, :email_address, :subject, :message, :user_agent, :source
    validates_presence_of :first_name
    validates_presence_of :last_name
    validates_presence_of :email_address
    validates_format_of :email_address, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i
    validates_presence_of :subject
    validates_presence_of :message

  end
end

app/controllers/ajo_contact/application_controller.rb
module AjoContact
  class ApplicationController < ActionController::Base
    before_filter :set_locale
    private
    def set_locale
      I18n.locale = params[:locale] if params[:locale].present?
    end
    def default_url_options(options = {})
      {locale: I18n.locale}
    end
  end
end

app/controllers/ajo_contact/contact_controller.rb
require_dependency "ajo_contact/application_controller"

module AjoContact
  class ContactController < ApplicationController
    before_filter :force_non_ssl, :only => :index

    def force_non_ssl
      if request.ssl? && Rails.env.production?
        redirect_to :protocol => 'http://', :status => :moved_permanently
      end
    end
    layout 'application'
    def index
      @message = Message.new
    end

    def create
      @message = Message.new(params[:message])
      @message.user_agent = request.env["HTTP_USER_AGENT"]
      if !verify_recaptcha
        flash.delete :recaptcha_error
        @message.valid?
        @message.errors.add(:recaptcha, "* Please try again")
        render :action => :index
      else
        if @message.save
          @email = AjoContact::ContactMailer.contact_email(@message.email_address, @message.subject, @message, 'parmalat-customerservice@bluebandmedia.com').deliver
          @email.deliver
          redirect_to contact_thank_you_path
        else
          render :action => :index
        end
      end
    end

    def thank_you
    end
  end
end

app/helpers/ajo_contact/application_helper.rb
module AjoContact
  module ApplicationHelper
  end
end

app/helpers/ajo_contact/contact_helper.rb
module AjoContact
  module ContactHelper
  end
end

app/views/ajo_contact/contact/_contact_form.html.haml
#contact_page
  %h1= t "contact.header"
  = form_for @message, :url => contact_index_path do |f|

    .field
      = f.label I18n.t('contact.form.first_name')
      = f.text_field :first_name
      .error= @message.errors['first_name'].first

    .field
      = f.label I18n.t('contact.form.last_name')
      = f.text_field :last_name
      .error= @message.errors['last_name'].first

    .field
      = f.label I18n.t('contact.form.email_address')
      = f.text_field :email_address
      .error= @message.errors['email_address'].first

    .field
      = f.label I18n.t('contact.form.subject')
      = f.select :subject, I18n.t('contact.form.subject_options').map{|key, value| [value[:option], value[:value]]}
      .error= @message.errors['subject'].first

    .field
      = f.label I18n.t('contact.form.message')
      = f.text_area :message
      .error= @message.errors['message'].first

    = f.submit I18n.t('helpers.submit')

app/views/ajo_contact/contact/index.html.haml
= render 'contact_form'

app/views/ajo_contact/contact/thank_you.html.haml
%h1 Gee thanks